[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3