export declare const config: {
    NODE_ENV: string;
    PORT: number;
    HOST: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    JWT_SECRET: string;
    COOKIE_SECRET: string;
    CORS_ORIGINS: string[];
    SCRYFALL_API_URL: string;
    SCRYFALL_RATE_LIMIT: number;
    POKEMON_TCG_API_URL: string;
    POKEMON_TCG_API_KEY: string | undefined;
    YUGIOH_API_URL: string;
    ONEPIECE_API_URL: string;
    MINIO_ENDPOINT: string | undefined;
    MINIO_ACCESS_KEY: string | undefined;
    MINIO_SECRET_KEY: string | undefined;
    MINIO_BUCKET: string;
    MINIO_REGION: string;
    CDN_BASE_URL: string;
    CDN_CACHE_TTL: number;
    ETL_BATCH_SIZE: number;
    ETL_MAX_RETRIES: number;
    ETL_RATE_LIMIT_DELAY: number;
    ETL_CONCURRENT_JOBS: number;
    ALGOLIA_APP_ID: string | undefined;
    ALGOLIA_API_KEY: string | undefined;
    ALGOLIA_SEARCH_KEY: string | undefined;
    ALGOLIA_INDEX_CARDS: string;
    ALGOLIA_INDEX_MARKETPLACE: string;
    COMMERCE_BACKEND_URL: string;
    COMMERCE_API_KEY: string | undefined;
    SENTRY_DSN: string | undefined;
    DATADOG_API_KEY: string | undefined;
    SLACK_WEBHOOK_URL: string | undefined;
};
export declare const validateConfig: () => void;
export default config;
//# sourceMappingURL=env.d.ts.map